# this is a UAT build with testscripts and production deployment container build images

sudo: required
services: 
  - docker
language: node_js
node_js:
  - "stable"


# using the Dockerfile.dev to test run test cases 
before_install: 
  
  - docker build -t ganeshssac/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run ganeshssac/react-test npm test -- --coverage

# building the docker container images using Dockerfile in the relative folders for production build.
after_success:
  - docker build -t ganeshssac/multi-client-uat ./client
  - docker build -t ganeshssac/multi-nginx-uat ./nginx
  - docker build -t ganeshssac/multi-server-uat ./server
  - docker build -t ganeshssac/multi-worker-uat  ./worker


  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  # Take the above images & push  to docker hub.

  - docker push ganeshssac/multi-client-uat
  - docker push ganeshssac/multi-nginx-uat
  - docker push ganeshssac/multi-server-uat
  - docker push ganeshssac/multi-worker-uat









  